#!/bin/bash

# List file ames that start with number
if [[ $1 = "" ]] || [[ $1 = "-help" ]] || [[ $1 = "-h" ]|| [[ $1 = "-s" ]]]|| [[ $1 = "-save" ]]; then
	echo "Script for cleaning filenames. Run in folder which has target files in it"
	echo "-n / -nums to clean numbers at the start of file name."
	echo "-u / -underscore to replace underscores with spaces"
	echo "-p8 / -pico to erase .p8-extension from filename ."
	echo "Use -s / -save as second attribute to to save filenames into textfile."
	echo "Like: cleanFiles -p8 -save"
	echo "Then data is saved to filenames.txt in folder it's been used."
	echo " It's formated like this:"
	echo "< Old Name"
	echo "> New Name"
else
	#Use /dev/null to discard data if not saved to file
	saveLocation="/dev/null"
	if [[ $2 = "-s" ]] || [[ $2 = "-S" ]] || [[ $2 = "-save" ]]; then
		# Create new textfile for filenames if -s is used
		saveLocation="filanames.txt"
		> $saveLocation
	fi
	
	for fName in [0-9]* ; do
   	 # Only process files that start with number and have space after.
	 	if [[ $1 = "-n" ]] || [[ $1 = "-nums" ]]; then
			if [[ $fName =~ ^[0-9]+[[:blank:]]+(.+) ]] ; then
			# Use regex before to clean file name
			newname="${BASH_REMATCH[1]}"
		elif [[ $1 = "-p8" ]] || [[ $1 = "-pico" ]]; then
			newname="${fName//.p8./.}"
		elif [[ $1 = "-u" ]] || [[ $1 = "-underscore" ]]; then
			newname="${fName//_/ }"
		fi
		# Print changed names:
		echo "< $fName"
		echo "> $newname"
		# Append to textfile or /dev/null
		echo "< $fName" >> $saveLocation
		echo "> $newname" >> $saveLocation
		mv "$fName" "$newname"
	    fi
	done
fi
